### ISSUE TITLE
Option to remove added characters like  '<', '|', '=', or '>'

### ISSUE THREAD

**Issue by youssefsharief** [neilbrown/wiggle#13]
Thank you so much for the awesome project. Can we have the option of not emitting these characters '<', '|', '=', or '>' during replacement?

**Comment by neilbrown** [comment]
These character are only added when wiggle cannot successfully merge the patch.
Just leaving them out, but including the parts of the patch that fails would make a real mess.

what do you want wiggle to do in the case that a patch cannot be applied?  Leave a .rej files?
Can you give me more information on when the current behaviour is a problem?

**Comment by youssefsharief** [comment]
Thank you, Neil, so much for your response. When I opened this ticket, I wanted to leave the patch with the mess that is made without these characters, but currently, I no longer need this feature. 

Thank you so much again for your effort

**Comment by neilbrown** [comment]
Ok, I'll close the issue then.
Thanks.
