### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jubalh** [neilbrown/wiggle#17]
Hi!

For the --no-backup option (https://github.com/neilbrown/wiggle/commit/d55ce20c7fa5301011396b6302c584b3680b2583) and preserving file mode in --merge --replace  (https://github.com/neilbrown/wiggle/commit/a9ac6337b9ab27d1f4d3258b244dab643c5c2420) alone it would be nice to have a new release containing these changes. Plus the small other fixes.

Would you mind tagging a new one?

**Comment by neilbrown** [comment]
Sound like a good idea.  I"ll try to do something over the next week or so.
Thanks for the suggestion.

**Comment by neilbrown** [comment]
v1.2 is tagged and pushed.

**Comment by jubalh** [comment]
Thanks!
