### ISSUE TITLE
mdadm problem in several places

### ISSUE THREAD

**Issue by Neustradamus** [neilbrown/wiggle#19]
Hello @neilbrown,

I see on http://neil.brown.name/blog/mdadm: "There is a git repository at http://neil.brown.name/git/mdadm or git://neil.brown.name/mdadm".
The git link is not good and it is not up-to-date (4.0 is the last): http://git.neil.brown.name/?p=mdadm.git;a=summary

I have found archived place here: https://github.com/neilbrown/mdadm with 4.1 release.

And on mirrors.edge.kernel.org, I see a 4.2 RC1: https://mirrors.edge.kernel.org/pub/linux/utils/raid/mdadm/.

Can you sync all?

Thanks in advance.

**Comment by neilbrown** [comment]
I have updated that blog page with current URLs.
Thanks.
