### ISSUE TITLE
Update brew install version to 1.3

### ISSUE THREAD

**Issue by hustcer** [neilbrown/wiggle#20]
Hello,

When I ran `brew install wiggle` on my mac I got 1.2 installed, not the latest version which is v1.3. Please update it, thanks.

**Comment by neilbrown** [comment]
This is probably the wrong place to ask about "brew".  I personally have only a vague idea of what it is. 
After a bit of googling I found 
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/wiggle.rb
which explicitly mentions 1.2.  Maybe you should raise an issue on the Homebrew/homebrew-core gtihub project - or even submit a pull request.  The best url to use for the source code would be
  https://github.com/neilbrown/wiggle/archive/refs/tags/v1.3.tar.gz

**Comment by geofflangenderfer** [comment]
I did some manual stuff to make this work 

https://github.com/neilbrown/wiggle/issues/24#issuecomment-1042620212

**Comment by geofflangenderfer** [comment]
in progress

https://github.com/Homebrew/homebrew-core/pull/95291
