### ISSUE TITLE
Wiggle for Windows

### ISSUE THREAD

**Issue by theomega24** [neilbrown/wiggle#23]
I need the tool wiggle for my work, is there a way to use it on windows?

**Comment by neilbrown** [comment]
I don't use MS-Windows and don't know anything about making tools run there.  If anyone else does and want to make it work, I'm happy to support in any way I can and would certainly be happy to accept patches or pull requests.  But I don't have the knowledge to do the work myself.

**Comment by jubalh** [comment]
@theomega24 can you not just install it over WSL?

**Comment by PaulBGD** [comment]
Running over WSL is likely going to be the easiest way forward, although in theory there's nothing _too_ unix specific to prevent this from being modified to compile for windows.

**Comment by theomega24** [comment]
I forgot about this issue but I did find a solution of just using WSL whenever I need to use wiggle.
