### ISSUE TITLE
Official release page

### ISSUE THREAD

**Issue by jpalus** [neilbrown/wiggle#26]
GitHub page links http://neil.brown.name/wiggle/ as a homepage. The latter shows list of releases up to 1.2. GitHub page appears to have a 1.3 release already. Can you clarify what's the main site for releases now? Whether it's still http://neil.brown.name/wiggle/ and 1.3 release should be uploaded there or is it GitHub page only and http://neil.brown.name/wiggle/ should no longer be referred?

**Comment by neilbrown** [comment]
Thanks for alerting me to this discrepancy.  I have uploaded 1.3 to neil.brown.name.
