### ISSUE TITLE
Build error: (-Werror)

### ISSUE THREAD

**Issue by Nefelim4ag** [neilbrown/wiggle#6]
vpatch.c: In function ‘merge_window’:
vpatch.c:844:16: error: ‘o’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   curs->offset = o;
                ^
vpatch.c:804:6: note: ‘o’ was declared here
  int o;
      ^
cc1: all warnings being treated as errors
<builtin>: recipe for target 'vpatch.o' failed

**Comment by neilbrown** [comment]
Sorry  I didn't notice this before -- I don''t use github much, just for hosting.
I should have looked properly before releasing 1.1 I guess :-(
Anyway I've fixed it now.
