### ISSUE TITLE
Build error on OS X 

### ISSUE THREAD

**Issue by TerryFranguiadakis** [neilbrown/wiggle#7]
[13:49:29] ~/project/wiggle-master :> make
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o wiggle.o wiggle.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o load.o load.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o parse.o parse.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o split.o split.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o split.o split.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o extract.o extract.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o diff.o diff.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o bestmatch.o bestmatch.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o ReadMe.o ReadMe.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o merge2.o merge2.c
cc -ggdb -I. -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -Wno-missing-field-initializers     -c -o vpatch.o vpatch.c
vpatch.c:2071:13: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
                        } while (!(check_line(pos, fm, fb, fa, ci.merger, mmode)
                                 ^
vpatch.c:2071:13: note: add parentheses after the '!' to evaluate the comparison first
                        } while (!(check_line(pos, fm, fb, fa, ci.merger, mmode)
                                 ^
vpatch.c:2071:13: note: add parentheses around left hand side expression to silence this warning
                        } while (!(check_line(pos, fm, fb, fa, ci.merger, mmode)
                                 ^
1 error generated.

**Comment by TerryFranguiadakis** [comment]
2071             } while (!**(**(check_line(pos, fm, fb, fa, ci.merger, mmode)
2072                    & CONFLICTED) == 0**)**
2073                  && ci.merger[tpos.p.m].type != End);
--> Added parentheses in bold to scope the value returned by check_line & CONFLICTED == 0

**Comment by neilbrown** [comment]
Sorry for the delay.  Thanks for the report. Fixed now.
